config/routes.rb
Rails.application.routes.draw do

  namespace  :home do
    get :home_page
    get :proxy_details
  end

  root 'home#home_page'
end

app/models/concerns/api_client.rb
class ApiClient
  attr_accessor :end_point, :conn

  def initialize(end_point:)
    @end_point = end_point
    @conn = Faraday.new
  end

  def get_details(ip:, type:)
    url = end_point+"#{ip}"
    url = url+'&vpn=1' if type == CommonConstants::PROXY_DETAILS
    _get(url: url)
  end

  private

  def _get(url:)
    Rails.logger.info "Get Details for: #{url}"
    response = Rails.cache.fetch("#{url}", expires_in: 24.hours) do
      conn.get url
    end
    parse_response(response: response)
  end

  def parse_response(response:)
    JSON.parse(response.body).with_indifferent_access
  end

end

app/models/concerns/common_constants.rb
module CommonConstants

  IP_DETAILS = 'ip'
  PROXY_DETAILS = 'proxy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home_page
    params[:search_query] ||= request.ip
    details = api_details(ip: params[:search_query], type: CommonConstants::IP_DETAILS, end_point: ENV_PROPS['ip_details.url'])
    @ip_details = present(details, HomePresenter)
  end

  def proxy_details
    details = api_details(ip: params[:search_query], type: CommonConstants::PROXY_DETAILS, end_point: ENV_PROPS['proxy_details.url'])
    @proxy_details = present(details, HomePresenter)
  end

  private

  def api_details(ip:, type:, end_point:)
    ApiClient.new(end_point: end_point).get_details(ip: ip, type: type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_additional_details.html.erb
<div class="col-md-4">
  <%= render partial: 'home/proxy_details' %>
</div>

<div class="col-md-8">
  <div id="system_information"></div>
</div>

<script>

    asyncDetails.init('<%= @ip_details[:query] %>')

</script>

app/views/home/_google_maps.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyANznm3MeZqxJsH-vnes0wTA_9mupLi5C8"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

app/views/home/_ip_details.html.erb
<div class="col-md-4">

  <table class="table table-hover table-striped">
    <tbody>
    <tr>
      <th><%= I18n.t('labels.ip_details.ip') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:query]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.provider') %></th>
      <td>
        <a href="<%= "#{@ip_details.org_search_url(org: @ip_details[:org])}" %>" target="_blank">
          <%= @ip_details.display_format(value: @ip_details[:org]) %> </a>
      </td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.hostname') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:isp]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.country') %></th>
      <td>
        <span class="flag-icon flag-icon-<%= @ip_details.country_code(code: @ip_details[:countryCode]) %>"></span>
        <%= @ip_details.region_country_format(name: @ip_details[:country], code: @ip_details[:countryCode]) %>
      </td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.city') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:city]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.region') %></th>
      <td><%= @ip_details.region_country_format(name: @ip_details[:regionName], code: @ip_details[:region]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.postal_code') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:zip]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.longitude') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:lon]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.latitude') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:lat]) %></td>
    </tr>
    <tr>
      <th><%= I18n.t('labels.ip_details.timezone') %></th>
      <td><%= @ip_details.display_format(value: @ip_details[:timezone]) %></td>
    </tr>
    </tbody>
  </table>
</div>

<div class="col-md-8">
  <div id="map_div" style="height: 360px;"></div>
</div>

<script>

    ipLocation.initMap('<%= @ip_details[:lat] %>', '<%= @ip_details[:lon] %>')

</script>

app/views/home/_proxy_details.html.erb
<% if request.format.symbol == :html %>
    <div class="panel panel-success">
      <div class="panel-heading text-center"><%= I18n.t('labels.proxy_details.proxy_check') %></div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-1"></div>

          <!--Proxy Search Box-->
          <div class="col-md-10">
            <%= form_tag(home_proxy_details_path, method: :get, remote: true) do %>
                <div class="input-group">
                  <input type="text" value="<%= params[:search_query] || @ip_details[:query] %>" name="search_query" class="form-control" placeholder='<%= I18n.t('labels.proxy_details.search_query') %>' id="proxy_search"/>
                  <div class="input-group-btn">
                    <button class="btn btn-primary" type="submit">
                      <span class="glyphicon glyphicon-search"></span>
                    </button>
                  </div>
                </div>
            <% end %>

            <!--Proxy Details-->
            <div id="proxy_details"></div>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
<% else %>
    <table class="top-buffer table table-hover table-striped">
      <tbody>
      <tr>
        <th><%= I18n.t('labels.proxy_details.proxy') %></th>
        <td><%= @proxy_details.proxy_format(result: @proxy_details[:proxy]) %></td>
      </tr>

      <tr>
        <th><%= I18n.t('labels.proxy_details.type') %></th>
        <td><%= @proxy_details.display_format(value: @proxy_details[:type]) %></td>
      </tr>

      <tr>
        <th><%= I18n.t('labels.proxy_details.provider') %></th>
        <td><%= @proxy_details.display_format(value: @proxy_details[:provider]) %></td>
      </tr>
      </tbody>
    </table>
<% end %>

app/views/home/home_page.html.erb
<%= render partial: 'home/google_maps' %>

<%= form_tag(root_path, method: :get, remote: true) do %>
    <div class="row ">
      <div class="input-group">
        <input type="text" value="<%= params[:search_query] %>" name="search_query" class="form-control" placeholder="<%= I18n.t('labels.ip_details.search_query') %>"/>
        <div class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </div>
      </div>
    </div>
<% end %>

<div class="row top-buffer" id="ip_details">
  <%= render partial: 'home/ip_details' %>
</div>

<hr>

<div class="row" id="additional_details">
  <%= render partial: 'home/additional_details' %>
</div>

app/views/home/home_page.js.erb
$('#ip_details').html("<%=j render 'home/ip_details' %>");

app/views/home/proxy_details.js.erb
$('#proxy_details').html("<%=j render 'home/proxy_details' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyipTrack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>